// This file was generated by Prisma.
// We load .env with override=true to ensure the workspace DATABASE_URL wins over any
// user/system-level DATABASE_URL already set on the machine.
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config({ override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
